# Generated by Django 5.1 on 2025-05-15 21:08

import app.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'state'), name='unique_name_state')],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('category', models.CharField(choices=[('C1', 'clínica médica'), ('C2', 'clínica de psicologia'), ('C3', 'clínica de estética'), ('C4', 'clínica odontológica'), ('C5', 'salão de beleza'), ('C6', 'clínica de nutrição'), ('C7', 'estúdio de arquitetura')], max_length=50)),
                ('country', models.CharField(default='Brasil', editable=False, max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=100)),
                ('public_phone', models.CharField(max_length=15)),
                ('restricted_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('schedule', models.JSONField()),
                ('closed_on_holidays', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.city')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('registration_source', models.CharField(choices=[('whatsapp', 'whatsapp'), ('website', 'website')], editable=False, max_length=50)),
                ('cpf', models.CharField(max_length=14, validators=[app.utils.validate_cpf])),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.business')),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('cpf', models.CharField(max_length=14, validators=[app.utils.validate_cpf])),
                ('speciality', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('phone', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.business')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DurationField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.business')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendado', 'agendado'), ('cancelado', 'cancelado'), ('concluído', 'concluído')], default='agendado', max_length=50)),
                ('source', models.CharField(choices=[('whatsapp', 'whatsapp'), ('website', 'website')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.professional')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(fields=('name', 'state', 'city', 'category'), name='unique_name_category_state_city'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('business', 'cpf'), name='unique_customer_business'),
        ),
        migrations.AddConstraint(
            model_name='professional',
            constraint=models.UniqueConstraint(fields=('business', 'cpf'), name='unique_business_professional'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_business_name'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('business', 'professional', 'datetime', 'customer', 'service', 'status'), name='unique_business_professional_datetime_customer_service_status'),
        ),
    ]
