# Generated by Django 5.1 on 2025-05-07 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'state'), name='unique_city_by_state')],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('category', models.CharField(choices=[('C1', 'clínica médica'), ('C2', 'clínica de psicologia'), ('C3', 'clínica de estética'), ('C4', 'clínica odontológica'), ('C5', 'salão de beleza'), ('C6', 'clínica de nutrição'), ('C7', 'estúdio de arquitetura')], max_length=50)),
                ('country', models.CharField(default='Brasil', editable=False, max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=100)),
                ('public_phone', models.CharField(max_length=15)),
                ('restricted_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('closed_on_holidays', models.BooleanField()),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.city')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'state', 'city', 'category'), name='unique_business_by_category')],
            },
        ),
    ]
