# Generated by Django 5.1 on 2025-05-13 14:30

import app.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_populate_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_source', models.CharField(choices=[('whatsapp', 'whatsapp'), ('website', 'website')], editable=False, max_length=50)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[app.utils.validate_cpf])),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_opt_in', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='schedule',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('speciality', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('phone', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule', models.JSONField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.business')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('business', 'name'), name='unique_business_professional')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DurationField()),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.business')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('business', 'name'), name='unique_business_service')],
            },
        ),
    ]
