# Generated by Django 5.1 on 2025-05-21 00:43

import app.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_populate_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[app.validators.validate_date])),
                ('blocked_start_time', models.TimeField(blank=True, null=True)),
                ('blocked_end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='business',
            name='unique_name_category_state_city',
        ),
        migrations.RemoveField(
            model_name='business',
            name='state',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(validators=[app.validators.validate_datetime]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('WHATSAPP', 'whatsapp'), ('WEBSITE', 'website')], max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'agendado'), ('CONFIRMED', 'confirmado'), ('CANCELLED', 'cancelado'), ('COMPLETED', 'concluído')], default='SCHEDULED', max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='business',
            name='public_phone',
            field=models.CharField(max_length=15, validators=[app.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='business',
            name='restricted_phone',
            field=models.CharField(max_length=15, validators=[app.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registration_source',
            field=models.CharField(choices=[('WHATSAPP', 'whatsapp'), ('WEBSITE', 'website')], editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(validators=[app.validators.validate_duration]),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[app.validators.validate_price]),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(fields=('name', 'city', 'category'), name='unique_name_category_city'),
        ),
        migrations.AddField(
            model_name='availableday',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.business'),
        ),
        migrations.AddField(
            model_name='availableday',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.professional'),
        ),
        migrations.AddConstraint(
            model_name='availableday',
            constraint=models.UniqueConstraint(fields=('business', 'professional', 'date'), name='unique_business_professional_date', nulls_distinct=False),
        ),
    ]
