# Generated by Django 5.1 on 2025-05-22 19:50

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_availableday_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, validators=[app.validators.validate_phone_number]),
        ),
    ]
