# Generated by Django 5.1 on 2025-05-29 15:58

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='schedule',
            field=models.JSONField(validators=[app.validators.validate_schedule]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[app.validators.validate_birth_date]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registration_source',
            field=models.CharField(choices=[('WHATSAPP', 'whatsapp'), ('WEBSITE', 'website')], max_length=50),
        ),
        migrations.AlterField(
            model_name='professional',
            name='phone',
            field=models.CharField(max_length=15, validators=[app.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='professional',
            name='schedule',
            field=models.JSONField(validators=[app.validators.validate_schedule]),
        ),
    ]
